CREATE DATABASE IF NOT EXISTS Log;
USE Log;

-- SAGA 主表
CREATE TABLE SagaTransaction (
    SagaId      VARCHAR(50) PRIMARY KEY,
    MemberId    BIGINT NOT NULL,
    ProductId  BIGINT NOT NULL,
    Amount      DECIMAL(18,2) NOT NULL,
    Status      VARCHAR(20) NOT NULL, 
    -- PENDING / COMPLETED / FAILED
    CreatedAt  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);
