version: '3.8'

services:
  jenkins:
    container_name: Jenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_root:/container_root
    restart: unless-stopped

volumes:
  jenkins_home: